<?php

// Onscreen debug.
error_reporting( E_ALL );
ini_set( 'display_errors', 'On' );

// Include autoloaders for namespacings generated by composer. This includes our own project.
require_once( "../vendor/autoload.php" );
